Do error checking on dtrx

diff --git a/running-all-students/generate-report b/running-all-students/generate-report
--- a/running-all-students/generate-report
+++ b/running-all-students/generate-report
@@ -91,7 +91,10 @@ do
                 exit 1
             fi;
             echo "-- Extracting $1"
-            dtrx -rn "$1"
+            if ! dtrx -rn "$1"; then
+                echo "dtrx -rn \"$1\" failed -- please extract zip manually. Sorry"
+                exit 1
+            fi;
             "${SCRIPTDIR}/clean-files.sh" "$SUBMISSIONDIR"
             shift
             ;;
